dist: xenial
sudo: false
language: node_js
node_js:
  - 12
cache:
  directories:
     - ./node_modules
install:
  - npm install
script:
  - npm run-script build
  - npm run build:compodoc
after_success:
  - git clone https://github.com/softmks/ng-mschart-doc.git
  - cp -r dist/documentation/* ng-mschart-doc/
  - cd ng-mschart-doc
  - git add .
  - git commit -m "build to ng-mschart-doc"
  - git push -fq origin master
  - echo -e "Done with ng-mschart-doc push. !! "
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/mscharts-angular
  on:
    branch: master