dist: xenial
sudo: false
language: node_js
node_js:
  - 12
cache:
  directories:
     - ./node_modules
install:
  - npm install
script:
  - npm run-script build
  - npm run build:compodoc
deploy:
     provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/mscharts-angular
    on:
      branch: master